#include <gtk/gtk.h>
#include <mongoc/mongoc.h>
#include <stdio.h>
#include <string.h>
#include <sys/stat.h>
#include <unistd.h>
#include <fcntl.h>
#include <errno.h>

mongoc_client_t *client;
gchar *url = NULL, *title = NULL, *id = NULL, *artist = NULL, *thumbnail = NULL, *video_ext = NULL, *video_codec = NULL, *audio_codec = NULL, *video_format = NULL, *duration = NULL;

#pragma region Base64
const char *base64_image = "iVBORw0KGgoAAAANSUhEUgAAAboAAAD4CAYAAACaECNWAAAAAXNSR0IArs4c6QAAIABJREFUeF7tfYd2HEeS7a328N57Q4IUSYkaSbNvd2f2nfM+fJ1WI2lmdmRIip4gPBretyvzzo2sbBQhkg0CaKDRiNKBADbKZN4s1K2IuBHhBEEQQDdFQBFQBBQBRaBOEXCU6Op0ZXVaioAioAgoAoKAEp3eCIqAIqAIKAJ1jYASXV0vr05OEVAEFAFFQIlO7wFFQBFQBBSBukZAia6ul1cnpwgoAoqAIqBEp/eAIqAIKAKKQF0joERX18urk1MEFAFFQBFQotN7QBFQBBQBRaCuEVCiq+vl1ckpAoqAIqAIKNHpPaAIKAKKgCJQ1wgo0dX18urkFAFFQBFQBJTo9B5QBBQBRUARqGsElOjqenl1coqAIqAIKAJKdHoPKAKKgCKgCNQ1Akp0db28OjlFQBFQBBQBJTq9BxQBRUARUATqGgElurpeXp2cIqAIKAKKgBKd3gOKgCKgCCgCdY2AEl1dL69OThFQBBQBRUCJTu8BRUARUAQUgbpGQImurpdXJ6cIKAKKgCKgRKf3gCKgCCgCikBdI6BEV9fLq5NTBBQBRUARUKLTe0ARUAQUAUWgrhFQoqvr5dXJKQKKgCKgCCjR6T2gCCgCioAiUNcIKNHV9fLq5BQBRUARUASU6PQeUAQUAUVAEahrBJTo6np5dXKKgCKgCCgCSnR6DygCioAioAjUNQJKdHW9vDo5RUARUAQUASU6vQcUAUVAEVAE6hoBJbq6Xl6dnCKgCCgCioASnd4DioAioAgoAnWNgBJdXS+vTk4RUAQUAUVAiU7vAUVAEVAEFIG6RkCJrq6XVyenCCgCioAioESn94AioAgoAopAXSOgRFfXy6uTUwQUAUVAEVCi03tAEVAEFAFFoK4RUKKr6+XVySkCioAioAgo0ek9oAgoAoqAIlDXCCjR1fXy6uQUAUVAEVAElOj0HlAEFAFFQBGoawSU6Op6eXVyioAioAgoAkp0eg8oAoqAIqAI1DUCSnR1vbw6OUVAEVAEFAElOr0HFAFFQBFQBOoaASW6ul5enZwioAgoAoqAEp3eA4qAIqAIKAJ1jYASXV0vr05OEVAEFAFFQIlO7wFFQBFQBBSBukZAia6ul1cnpwgoAoqAIqBEp/eAIqAIKAKKQF0joERX18urk1MEFAFFQBFQotN7oOoIBEEAx3HkOvyZm/m3+dn3ze/5xV974WelYhHxmDnuQ5uDj/++6pO74RdwXQ/pTBqe58P3XPnZLLVZWwS+/OjEYrJPPB6H53nyXTdF4LIQUKK7LKRv6HWiJOe6LhKJhJCd7/shyXlIJJLy8/b2LlbW1nGUy8m/Xc+H45H2wofmezAMefOGonv103acGGKxGFy3JATX2JhBMplCR2cb+nr74JRfZnzYfbn+JDveC7opApeBgBLdZaB8g69BQuODkFuhUEA6nZafi8UikskkXN/H1tYOVrNZ7O7uYm//EIViQSw7HhuvaLBV3OEGo1/9qVsrLfB9ODEIeXG9m5oa0dnZgeGBfnR3dwux0WK39wLXP5VKVX+AegVFgB6kwPqSFA5FoAoIBHRd8b0+COTLuq7sQ295bROv37zByvIKd5O3flp+3JcPRaWxKizKBZ7SWmY+rXTPQyweF3ezfawM9fdhcnICfX294rpMJuJla966qy9wOHoqReC9CCjR6Y1RZQSMi7JUcsWlxQcgf06lktjc3MLffn6Eo6MjlEol+R0ffplMBo2NjUJ0vk/X5Yc3fU+r8vJVOH0qmRTrnCRG1yXXMV8ogBZePJaA6xbR09ODz+9/hra2diQSMTD2Smsu6ta+2lno1esdASW6el/hK56fH5QQc+LyAEwm02XLjgKUH374G1Y3N8WlSVJrbm5GT083Bvr70dCQRqnkIZWg2/Njdt2H43dXPPUbcflYPAa3ZF5GSHSHh0fY3NzGxsYGtre3EUskZO0nxkfxh4cPkU6nRKBirDmunXFr66YIVBMBJbpqoqvnhucX5M1e1JReUBYgLMwv4/vvf0C8IYNCPo/2jnZMT02hv7fbWHMO4PkBEvGPPwjVorvam8zzSkjEE0JcPtfY9VAoFLG2vo6nT5+i6AP7+/sSm/3j119haKAfqWRc3NO07pTornb9bsrVlehuykpf0TyDoGRib4gjny+KW5KW2vd/+RHr6+so+B6am5swNTWFqYkxpFNJsQAS8TiMhuXjUToluita2PCyQeDJCjF9gOFYWurxeALFYglLS0v46y+P5WWFa9rT3YV//uM3aGxImzhdwJieUdzqpghUEwElumqiq+dGQHl5GHtjzhVVeeubO/if774Xi+0od4Bb09P47M4MWluaAN8Ty8Cq88L0O0WyhhEox9pkqQMhPW4ku7/8+DdR1CaSSbHq//yv/4K+nk4jXInR3an5dDW8tHUzNCW6ulnK2pyIRNBCorOJwvPLWfzw41/hIwa3WMDnD+7hs5lb8uYf+C6cmMmv4rGquqzNdT3tqJ789gy/PH4irstiycX/+ac/Ymx4AJ5LcRJJTmN0p8VS9zs7Akp0Z8dOjzwFArTO6NOihWaJ7s38En7869/gxJNwAg9ffPE5bk+OIUbzLfCA8C1fLDtlulOgXLu7zL6dx99/+lnSSo5yefzTH7/B1PiIWHQao6vddau3kSnR1duK1th8SFasjiFiBSYVOw5evV3A3/7+v4gnU4ghwJcPv8Dk2LAQnbXoJO8OjhJdja3npw5naXkV3/OlxnGE6L75+ivcnho3cT1VXX4qnLr/GRFQojsjcHrY6RCIui6tcOTFmzn8/X//gWS6AfBdfP3VHzA+MmhcnGCFjYQhRU0YPx3INbzXyuoavv3L92LRM7/u668M0Yn1DuZYquuyhpevboamRFc3S1mbE4kSnR3h89dvxaJLNzTBKxUkbjM61B8mGfNVP24qazDXqjanpaM6JQKr2XX81/98JyIkph18+eVDzExPvGO9n/JUupsicGYElOjODJ0eeBoETIjOxOisOo9ER4uORFcs5PCnf/lnDA/0GqKT4pasiKIW3WnwrfV9smsb+M9v/0fqmhaKJXz+4D7u3JqSMmG+V9L0glpfwDoZnxJdnSxkrU6DRGek5Ibo+P0FLbqQ6Ar5I/zbn/4VQ/290ubFChQoXGHdRLXoanVlTzcuWnT/8d/fiuqSFt39+/dw9zYVtqyHyULPml5wOiR1r/MgoER3HvT02IoIWDGK3ZGihOevZ/G///gZiVQGbjGPP4dEF/jsU2YsOhWjVIRWdni3v9/vj4l2j6i07+mu+Gl7LWfX8d/f/o/k0ZHoHj78ArenJ6UrRUzFKJ8Gpu59ZgSU6M4MnR54GgRsikD0Ifvs1Sx++vkXxBIpidH925//hMG+njANgWc1AgVNL6iMsHUHR3v88ajjRrbGin4fKUZJsPKVzrbH8to6vv32O7HOSXRfffUHTFOMgiBswaRilLMhq0d9CgJKdJ+Clu77yQgo0X0yZJ90QPQFwrZCst3cLeF9yPK7jE7fSnSftJy6c5UQUKKrErB6WoOAEl1174T3tbqx1h0tNtvF2+4XJcHLaJOjRFfd9deznw4BJbrT4aR7nREBJbozAnfKw8pNilhnMjyGCfomxsk42LGchyQXLYIdJb1TXu6Td1Oi+2TI9IAqIKBEVwVQ9ZTHCCjRVfduELFPyGVMPbSbdWOyhNrJTt7SOYAkGMbuqjlCJbpqoqvnPi0CSnSnRUr3OxMCSnRngu3UB0meYgDp78ZO32xiS9GH6frtoa21WdyX7OjNFkk2zYMXUIvu1DDrjtccASW6a76AtT58JbrqrhCJrlBwsbu7h93dXRwdHQrpkcSE1Hx2dk+ipaUFnZ2daGpqkgLLl7WpRXdZSOt1PoaAEp3eH1VFQInufPBawUhUIUkiI1mRzIpegGx2DRsbm/A8V8iNvzdClCR835W4HMmuMZNGe3s7+np7xN/JRP5qk95piY7j5ZedF1GLqkij8UVriV6GmOZ8q6dH1woCSnS1shJ1Og4luvMt7MeIjmde395DNpvF3t6ekBldlOzmTWK0iktr4SUcoLm5GSMjw2hoyJRLs51vhB8/uhLReR47kpvaplHiKscYWdg7DEK+j/guw/1aTXz03JeDgBLd5eB8Y6+iRHe+pbdJ3bbFkbVs+J3xuJez88jlckJuJDrb949XJYFYS0kEKb4nRNjV1YXe3h6kkqbBbTW3SkQXBM7vYoV2rhzXSSI7SXbVHLueu34QUKKrn7WsyZko0Z1vWSzRva9819bWFtjyyMbjPpQ+UK6A4pnYHUUpY2NjaG5qON/gTnF0JaKz5d7sGKNE/j73ZfSzy1CNnmKKuss1QECJ7hos0nUeohLd+VbvQ9VLSHyLi4tYXF0XF6W13qLuPxvzKp/Dc2Uw3OfWrVuiyKz2dhqie198jp/ZIuCW5KPEdhV1O6uNlZ6/eggo0VUPWz2zVkY59z1wsh5lNGb39u1bidGR5KIuSxIf95MOEDHT8khIQrpDsC9cAXfv3hWLrtpWUSWio+vy5HZSeGJJ7WR1FxWjnPv2ujEnUKK7MUt9NRNVi+58uJ+sZBJ1Zc7OzmJ9a9d0Yo9UPbFKSmsVlcUcbkna5TCm9+DBAzRkUjVBdHZ8JGbrhmUeIMfZ0NAgcUVu/D3xsCKbyyhKfb7V06NrBQElulpZiTodhxLd+RfWEhYJLOrKXFhYwMr61judCuzVbDUUa9UJURQLQhxHR0d4+PAh0qlE1ZPGK1l0VF2etCqtW5YW68zMDDo6OoTsrJVqie4yilKff/X0DLWAgBJdLaxCHY/huhPdyVjQyf5ulyFvj47BKhL5nRbP05evQisoUVZYAo78RwLJlfJoSGekgW0+l0MqEUdzUxMmJiaQTiW5a1W35bUN/OUv3wtJFXI5/PM//x+Mj4+iVHKRSdHFCrjsQxiLm9y+AFhdXcOjR49xlDtCW0sjpqamMDQ4iFSSeYE+Ys5x2yGHNc50UwQqIKBEp7dIVRGoB6KLklnUiriMGNH7rsHPrJX3cvYtDg8PUSy6YvXQ2iGJeK4n6xpLxhEPk8jdUgnNDRkM9PdLlZREPFZ1oqNY5ocffjCke7CPb775BtPTk5D8OV6eY6NIJoghlohhc2sHP/38K3K5gpQxy+d2xM16d2YGmVTa3Ku8qbgxv055rqp/v/VyciW6elnJGp3HdSc6wnpSyWhdbZcRI/oQmVqi28/lsbq6CqYaxONJSR0gGZPoHCcGJ+6YBHKXFlQS3cyh6+lBJpMGfB8O2aaK2/LaJv7rv/5LSJiu088//xy3bk0jRkuM5lwYWyyVPOwdHuLXXx9hc3NbCNDzfLS1pjFz+zZGR0aQiJnEchKdvHwo0VVx5err1Ep09bWeNTebeiC6D7krL4PoPragErMKgO3tHWxsrOPg4BC+kEBMLChTIswVoyeTSqG9rVXiXVRb2mok1Xa9Zjd38B//8R9l1ecXX3whrsh4nM5VgH0USq6HXC6Pf/z0MzY2NuB7hsiaW1rw8Iu76GzvQDqThu8aFWmMR9qWDWrR1dzffC0OSImuFleljsZUD0QXtaou23VZ6VZwmW/m+zg6ymNnZwcHBwdwXdOGR/LoEnFRWra2NKOtrU3icrSmqk1wdtyM0f3441/FqnQLBXzzzdeYnJyQMbDWZhCPC0HTktva2kY+nxdDj4Q8MTGOyfFhJOPH6RK2FqZUSPF8xBKXV6C60lro72sXASW62l2buhjZdSe6KMkxZsQvEgfLbdXC5gfG+uE4i8WSEAqtIyNaiSOVjJfb9KTSyUhIy9aWrK7rkjG6v/zlLzLGtuYmfP311+joaBPoSNDbB0d4/eo1qLC09TnTySTu3buPwcE+iSMmE6ZUmV2LchkwSm5UjFILt2HNj0GJruaX6HoPsF6IjgTCOBil+ewAwC9ul2UZfewuYNFmPvzjCZMuwPgc+4tTnWjHV/b0yQ/SxS5MVaguYdOi+/d//w/09vbizq1pDA4OlNMh8rkjPHnxGnNzc2LdkegYY3zw2T309/ejqSn9TuHpaOK4zPcS2w1d779CHb0Snd4DVUWgXoiOLsH5+XlxDfIhPDAwUK5IUlUAT5z8ZLqDTbI+Jl26Jc1BFHMwnmWtHj+glcffG9WisZCq6/pbyq7jb3/7uygnRwb7w5w5M8Zff/kZs4srYn2yWgvTHqanpzE1MY5kIg7f8+U7SftkLUyxWBmvs5O9zEXQa107BJTort2SXa8B1zrRRQUl74u/MdpF6X52bQ3ra2vS662puRk9PT3o6e4EPWdCIAHeTXwOFYXV1r+fVGWWLysxOuPWtFxwvG8ozzc26YXfUFEyXtnMopjLo793AIHH7gkZij3x6MljzC8sohgAxTwroGRwa3oaE2OjaGxIC4H5PsUnhoh/P08qNk3GoG6KQCUElOgqIaS/PxcCtU5070sdsHlqUokEwObWrkj4KZSwrkD2devr60VbC5OxzeP2/W7M6sbAzrU4F3RwOWYWMmoUh6PiEVKJpLwIBD4FKAFevZ7Fs1cvgFgc+UJRBDKjo6OYnppEa1MDHFiCJiHXP34XtAx6mo8goESnt0dVEah1ouPkT6YJRGsuHhVLWFxclvgck7Epb2e8jiTY1NSEsZEBNGRM5RFaU0EQFlC2RtMNca1F++VFb6gAnrgg6SKlSvLZi5d4/XoWLgIUikWx2FilRUiuuRFxm18nLw5KdFX947xBJ1eiu0GLfRVTvQ5ER3ekrZ9oiU9EHZ6Hta1dLC8vizXX2NgoEJLobC3JoYEedHV2IR0WHi6fSyyY6idkX8WavkNkEdVn1JKzVjFfAJisnkim8Or1a/z29BkYOfQCH/liAdMTk5icmkJXe6u8KUhR57I3kkSnrsmrXuN6uL4SXT2sYg3P4boRXdSVubu7i4WVNezv74slx+oeJDJutOhIeE0NKQwM9KOro1M+L1uHN4ToiMc7uW0hWZWxcGIiNFnb2MCvjx6jUCyJOnRvfx/Tt25hZmoSbW2tYskxFkrxiVRN0U0RuEAElOguEEw91e8RqHWiiwonTubMMS63ur4lYnzmzfH3JDeSHi1AaRvjldDT3Y2+3l40NkY6dkvONhUq9f3Qjgp4TjZQFWwdB2/fLuD5y5fY3d+TlAce09fTi4dffoHWpkbEwzJkohINk9kvo46o/r3eHASU6G7OWl/JTGud6KLxOfszH8Sbm5tYW1vDYeHYrWnrSxJI67oMwh5vnR0d6O3tQYodAUhxHgsW17/n7aSYh3O3tUD5UrCytoGnz55jY3tLLOJioYi+nh589fkDtLe2I4iZTuLRnDj78mFxvpIbVy9aVwgo0dXVctbeZK4L0UUtO3YDYFyOrksnmTE1I4tF+W7dl3TZSbcAByZ+19CAkZERtLe3GlEK+6zF67+6fpSU+LMlOeJFl++PPz/C3t4e4skECsUCuto68PXDL9DT2QGwaUHClxgeS5VRsGL75xHrq64lWnt/TTqisyKgRHdW5PS4UyFQ60Rn3WtUS0o/NC/ACl2W2aw8tINQ3m6VmLQ8oi465nvxd77vSpxuaGgQmXTa1GGMtMGx4gxbbPmdeF6IZLTyR9liDGNetI5s2TEreKkF956MISCh0zJjEndcuuiIJff8OdbXN6Vk2uHhAfp7u3H/s8/Q09VhxD+eD/bqCSLdCKJzqoX5neom151qHgEluppfous9wFonOiEcicKZbWd7D8vZVamAwodxwIf4RzbP981+TG52HHHLDfT3IU4CDIsqiyuTZt6JXDtrsZyME9rL2RqWVgHKPnM8TZo1K6W819XfGwXJg6NIp4gECyw7juQd/uPXx9jZ3xcy8zwXba2tuH/3DoYG++HAVDWBvFyYOpa6KQLVRECJrpro6rnl7d6kRh0/6J+9msVPP/+CWCIFr1TAv/35Txjs65EHH59/NknYHltNGMXSCutCFksu5ufmsb23K9Ycm4NaV9yHxuB6pnUMCw+XSkWk4nFMjI9LSxzX9ZBI/r7E1klis/8+ea13rRtgaWlZcGS9SLvvVZOdUaESJ0fSKXL5An759TfMLS0jnWlAsZCT0l5sz9Pf0yXJ4MkkyS0w6RcxJbpq3t96boOAEp3eCVVF4LoQHV2WOzu7WFhYQMF1kU5nJJWgUtHmWDwu8vlyhX3XRWdnh6QcMJFcCOCENfchC+6kJWcsPsaugM3NLaysrIrblLU2e3q65bxXL8Wn29a8xBwd5fCPn37B1vY+XD8AXwIy6QTu37+P0eFBSR1gl3NuJDtawUp0Vf3z05OHCCjR6a1QVQRqneg4eVp0uzv7Uubr8PAIPpOWjWlZJqkPgRRPJEWowgKOiWRCioExVtXV1YnR4SHJD4uWyLLEaa21k01d7efWbekHFMIUpMI/x8bfU/jCaiJsRnrV2Qv54hHSqQzyhQJ++ulXrKxm4boBMpkGuJ6LLx7cw8jIkGRaWEtOEsjZaUFetWvA/1rVvwA9eS0goERXC6tQx2O4DkTHDteLi0tYW1tHMplCEHMkXy6RYO6caWL6wS1w5KHN/blvMmWIL5NJY2R4BF3tLWXCPGkd2nQFK623hBh1YeYLrhAwFaA8L/eh2rOzsxPDwwNXXr2/5LlwSy4eP32GuflFGZ/v+lK/8vbt25iaHCunDrBfHoU7TY0ZcU+T45Tn6viPv4ampkRXQ4tRj0OpdaKj221rewfLyytiMbEfmu8ApaKp+CHViD+y0eVJNSRJixYMk5/ZDJVkxcLPowO9aGhoeMdCtITHY7idtB6tNUfy3NjcEZelFaSQSEisHNvIyDA6O1qv9LZxvQA///oIr2dnESCOdCohsdbx0WHcnbkdKkVNDzwWc+Zcp6YmJMFQ8ueu2iS9UvT04peFgBLdZSF9Q69T60SXyxUwNz+P3d39cr1L0g9jY0JEFYgu5iTEtSgFnxOmLBitFP6bMb6hvm50dXYK2XE72QrIeO+O3ZvRPDTpgbewIufhcZTpc0zGYszI18ztyYpxxGreeo+fPMeLV69RYOxNWup4mLl1C7cnR5FMOEgmG2R8r6XO5XNMTU3h7t2Zcia98lw1V0fPbRFQotN7oaoIXDnRhflxZpLH8SAjCHHw8s0sDg4OhUxIbuI+DFWYtMwqudYo82fMiQTFvDmWseJlJL/O95FJxKS7dn9fr/jpyvvGYu8kRJfz7MKu2dvbtORWcJgryLlJcPG4USuKmpN5aAgwPNAvFVlM1/CwVVA4Z8lrO2dj1eOyylK8U+bHuKQbAM+fv8SLV29QKhZRLJWkp9zYyDBuT0+Ke5J61lg8JQTHBPxsdg1f/uFL3J25JfhQgalFm6v656cnDxFQotNboaoIXDnRwTf9c4SxYuUGnjTW9g8OhOii1T0uGgyWCGttbcXg4CBaWppEUl8mpIg1Z68bwBEX6sbGhpQhC8LGox8aV2M6hbGxUTQ1NoRkSKsqnLNc6HwdxElFvuchHndEMUmVaSyWwJPnr/Dy1Wu4no9iIS9kPDY6IrlyzU225qePvcM8/vvb/5FizpzX119/hZlbk5JnyHw67Td30Xecnu99CCjR6X1RVQRqgehMvhYf+Mai48O7UChJKsHO/sHv5P8n282cByBem5XAOjpMygFFKiReuiJNQnpQJiiOK58viiVH8YlHI6rCxQPXlQaww8NUNhoSZZzQSPepHD1f41KfZCTpA2YkTKB/O7eAR0+eolAyOXTchgYHJSbX0d5y3IQ28LC0tonvvvteXjSYXE6iuzU1LmpR5wIszvOsjR57cxBQors5a30lM716ogtCInNMLExa6QRYX9/A4uIifKm8bLaTqkgbOzsvcLSIKFgZ6OtFX1+PEZZEeuDZMmSlkicNXpdWViU3L01hTGgBfmgMbiFvGsCOjaGpqVEIxCS7h2Kac/ZzK3kFJOOmcwPXkk1of/nlCfJstxNPoOjmMTQ0hHt3ZtAR1vn0PTcUoQRYyq7j++9/FNLN5wv48ssvcXtaie6895Qe/2kIKNF9Gl669ycicNVEF81XYzsBejD39w/xdn4BuVxOXHEnt/eV6/rEab+zO4mHMUDmvzGGJS7MMEZoY4CMuzEut7axicOjo9AyMzHDj21iuTkOOtrahHAymZSpOBIKXCpVdqk0L9crCknFnDjevJ3Dq1ez4oJkOTK+MAwP9eP27Vvo6e4UDzFjbyY2aKzn5bV1/OUvPwjOuVweX375ELdvTSKhrstK0OvvLxABJboLBFNP9XsErprorMrR82nZcXwBFpdXsbS8LKrFKJHYn6OfVaqMUmnNKUhJp9JSHozWWV9vD4YG+k1lkDB0yO+7u3tYXl3F3r6pscn0AZYkqyS/t1X+SXiT4+OSqO57rL/5rtil0jg/9HuSFuNwy9k1PH36XBqmiiLVddHW3oaHD+6hu6sLDnMPiyWk0yk5lclDTGBhZRU//PBXabZKi+4Pf/iy7LpkyezzulbPOi897mYhoER3s9b70md71URHq8O6LGk17eztYXmFFVAO0djYWO4YXi1gOP9EnJaZL9ciufb39aGro80UQZbSWXlk1zewsbkp+zCNgKYnE6wTYVPSDxORmR9dneyJNzw4IKkMJDoy6bmJ2g2wub2Nn375FfusGoMAhVwOoyMDmJ6aRF93TznWaOOO/M4vJrYvZdfEdWlKpRXFopueHBPFJWN0FLbopghUGwElumojfMPPf9VER5uByd/JFPPdXLx+OydCDz6ErRDELlGUFKKlus6zhLG4qZpCC43WGX9mIvlQfx/a2kzVlI2NLSytZiU/jvvRwqMlyK1SnpklFH7n8SODA6LwpPWYTMbPGaED1rPb+O35M6ytb8JzANd30d3Rjjt3JjHc34dEPFWOB0Y7PViXsXVd0v1J16WKUc5zN+mxZ0VAie6syOlxp0Kg2kQXrfDPAb1b8T9AyStJfInb6tqG9JojkaRSabGCql0UmYRZovAknhD1hxV7AAAgAElEQVR3pW3gSncf898YU2Me39z8Qhj3ouXnibuTlVYq5fFJmyCSaDwuDWDZC294cEgawNKqq1RJki8CvA5xIKmy0gtFJsRob2cf//voCTY31yV/jvmFba3NeHDvM/T2dLGVHBIJxgQDcV2+LyeOFh1Vl1aM8tVXf8Ct6QlwRWKSjH8+VeipbkLd6cYjoER342+B6gJwlUTHmXm+K89fClAYm9vfP5B6lkw3IOlUcg1eBDq2cLOtliL1Hpua0N7ejv7+HiFntuDZ3NwuqywT8aRYf9Kl/CObCP+DQLonmAawPjrb2iWVoakp81H3pX0pYJcBkpYXpiQ4iGN//whPHv+GxbWsnIMu1Y72Nty5NY3hoQEZEXPrKrkeadF9++13ZdcliW6a6QUsGCZTU6K7iHtMz/FxBJTo9A6pKgLVJjprxfH7++JRtEKoYlxbW8Pm9i5c1zRKpQJThCqVfIPnRMeKRaIdw20si+7ToaEB6V0nyesv3whRMUZXLBTFQopkP7x/JKG6Uuwpdkj3faTiCXR3d6O/v1espg8pL7mvQ6JxDJGJ29SBCGKePXuJxYUleDA5f21trUJyI8NDUrDZiHxMEv7HNiW6c95AeviFIKBEdyEw6kk+hMBlEZ0pkWVclNH0AF4/u7aG7Ooq8sUiYvGkyTMLRSoms676W7RbuB0jx9na2izFmZlnR3KxIpncUf5URaWliBYJLmwAKzl6RRMHZBJ5S/NxQWl73WhR6RhiplZnKinknysW8MujR1hdzqLouqKupPU5c2sa42OjEtu07wYmV+/jYhIluurfW3qFyggo0VXGSPc4BwKXQXQcnnUPnuz9trt3IDUWmYjtJOLithRVoM9YVLxcTeQcU/zooZaArbXFna2FZdr0eNJIla7G5eWs1ISUbggSK4vDD7yPnl9idImEEB03HkOi43e28hkc6C1L/k8SnbguEdbfpPy/UMJPv/6C9Y0NlDwPhWIRzakUbt+ewdjosMQ1aQEzbkgMOadKeXpKdNW6s/S8n4KAEt2noKX7fjIC1Sa6k2KU6MOcRDI3vySdwynUSKRT5d5xJAhaI9W26E4SnR0vCYI/u67pRMBGqp4XYHZ2VmKHyYTJR2Nh5I9tjK+JKzZSSiwWGOLn50wDoHVHS+wk0UXPe3RUxNNnz7G4vISDoyNRqbJg9d3pSam60txsktyti/R9uL9vnEp0n/wnowdUAQEluiqAqqc8RqDaRHeyQ7d1y1HIQTfg27llEXWQMhy62ags9L1yz7hKqsSLWstoKx5LEiZuZ2JgPT09aGvrkFji9va2EJ3J//s40bHDgliJEXkmkwp4DZ63s6NF4nUsLG3JNZo64fq+lPb67bdnmH3zVly7+QIrswS4PXMLd6Ym5TiSMTeek/8+6Yr9EE5KdBd1B+l5zoOAEt150NNjKyJQbaKLWhbRXm97e3tCGlvbB+LGkzJc4iqkFF4CW2bsFUpsVZxghR1M3UnPNBmNx8sNVHlYlOj4u76+Adk3m82KSOQ0rkuTiF2QFAPb6ZxEx2NFtel4GBgYkFZBdIlGN+ltF7h4/Zqlvd4gd1SQGs3Mv6Po5O5nt9GcSYcvBSRPUy+Um33BqJSQrkR33jtIj78IBJToLgJFPccHEag20bEljSml5UiuFx/8jG/Nzc2L2jJfMLUa+Xym9VPu2HNJRBeNzUWVlxYw5q+xegsrpzQ1NQshswYny3iZYs8fv7lIcKLQjLHJqel0Hq11GY8lxWocHuxHT08HAqYgsN8e0xc8Dy/ezOENG6cWCgi8AKViAdNTE/js7l1JT4jxrcA0CDfd404QXaVbX4muEkL6+8tAQInuMlC+wde4DKIzhlnICI6D7e1dqbIvnbkvSVV51iW2LkAeby1P/my7ilcSe5jpmaKZUfeoFYpQo+IEHqYmRtHZ2YYSrb9kEoETk158T56+kjglY5hUU06MjmDm9rQoLZlb55yzRJcS3VnvDD3uIhFQortINPVcv0Og2kRH1aKxmvhQplS+hLm5BamwX3RNo9Ba3k6qMa3VZ5O/KxGdddfa89AKtDE042L0MCAdzsOalL4vitOl5VU8/u03HOUL4i4lWbJ82P1796T6ieT6MU/unI1blehq+e67OWNTors5a30lM6020fk+y1dRhs/pOdjY2MT84hKY+UxlZaXKIlcCSuSi1gqT5O3QKjtpmVUaYzRv0LoWndBN29PTLo1Z06mMlPBib9alpRVRWDL1IpVOYnd3R9oHff7gQdmSM/FEg+l5NiW686Cnx14UAkp0F4Wknue9CFSb6EwcyzyM9/YOpGkpY3N8oIvKsIJq8aqXLUpqQivhXKIuzY+NkRarWypJPM92LKd5m0qmpDvD6EivJIKnUhlBYn5+CW9n57C9syvWL4IS+vv7cGdmRmpvGnGOsQpPm0LwsfEp0V31HabXl7+roFJnR8VJETgHAlUnOnksB/A9YH5xARub22CdSKljmUqCfdpqeYtK/aPj/NDnJ+cSxBwEXmgNhvL/ZCyOrs5OKbycyZDsY3BiSaysrUtPua2tHXk3KBWL6OlsxRdffIGuri7BkeIWblEF63nwU6I7D3p67EUhoER3UUjqea7GopM4VIDt3V0sLC6LejCVTKNYKiKeSAIVKovUyrKdlthOjtdlcWSqSqmKZJJ4LI7Wlhb09fSipaUBXimPeCqNldUN/Pbihbgrc/kc33ClYerD+3ekgoppD2QsOZsOIYno59yU6M4JoB5+IQgo0V0IjHqSDyFQbYuOlUEoRHkz9xY7O3uhxJ62iWkb46C2Lbpo8jgxjHY5r5SjJpaXY9SagesJ0bFzweBgPxrSaam0kogH2Nndxy+Pn2JpdRWpTANKbgEtjY34/IsHGOnrkRY9bLXDtbKEZ9fzNGP42N2vRKfPhlpAQImuFlahjsdQbaIrlDxsbW5hcWkp7M6dCVWEDmLxWLkGZO1CLNlp7xnehz5/d1fWwmS3A+betbW2YHRkBI0NGSEu+if3D/P49ZdfsZLNIpVOYX9vH61tLfjjN1+JRZdiJ3Jh2Hfz5C4KLyW6i0JSz3MeBJTozoOeHlsRgWoTHaXyW1vb2NvbF7ebTZo+LvL88RJaFSdwDXawndK7ujrR1NhQrsLCOOXff3qElZVVaYxaKhXRmM7g888/l/ZA3FLJ6qZfKNFdgxvoBgxRie4GLPJVTrHaRMfzl0qu5IvRBcdCxMcdDK5y5pd17bAiTMyRws2ssMItl8vj+fPnePHqLZIpNnEtIpVI4sH9+5iYGJPamEapWd3Gp0p0l3Uf6HU+hoASnd4fVUWg2kRXctmFwJT4Eg9c2F7ukip8VRW705ycVU0YjzyO9QFHRzm8fP0GT578hnSGFp4vykwmg1uSS6eTx+XQTnOhM+6jRHdG4PSwC0VAie5C4dSTnUSg2kQnSeFUHYaFhlnPkv+21fzrPXvGEpwR3wCHuTxev36D2bdv4bqe9P+mG/f2rVu4fXsKmXRarF9utlFtNe9aJbpqoqvnPi0CSnSnRUr3OxMC1Sa66KCi1UWMdReUE7DPNPhrcFA5Fhm6K1++nsXbuXkcHBygsamJRTMxNDSIe/c+Q2MjRSpMpGcqArGJdHGo0lyV6KoErJ72kxBQovskuHTnT0Wg2kQXtdiiUvhoWaxPHfN12t8mdufyRbyefSuWHDs2FEuuCHOmx0YwPT2JxoZGicfRteuWitJpXbbzVfiqCJUSXUWIdIdLQECJ7hJAvsmXqDbRWctNntlhYM6KUSoVRK6HdTFdyl3Mvp3H46fPpJkBySxXKGFqagoPZiYl/cBWPJE6Mr5JMheLly0Kqrgp0VURXD31qRFQojs1VLrjWRAwXWToJjMP5EQihWcvXuHXx0+lBqNfyuNPf/4X9Pf1slCVia3Z/mfSJPXTH8TXyZp731hPJo1He8CZn31JhafvkdG25y9e4s3rt8jlirJErO/Z39ePzz+/h7aWJultR8GOEeqE7lzJm7sY167pfnAc87PpDvxseX0Tf/3xbygW2SXBxx+//grTU+OS35hIMLWhyiblWW5aPabuEFCiq7slra0JURxiQkEBPNdFPJHC8xev8NPPj+Akkgi8PP7vn/8sBYVJcqaYsQdHTEFpiFZbE7rg0XyIlKOfH6dLGFIQqguMCOf5m1m8fPUK+7uHSMSZXhBIZZR7d2+jvb31UmgkOr6yOCaMjy5mN/Hdd98J0RYLBXz18Avpd8eXnpMdzy8YWj2dIlBGQIlOb4aqIuAFPuJCVqbzNfub0c323fd/RUNTMwr5ffzpX/+EkaEBIUJ5+NEdVyqaBqGX8qiuKgQfPXm0S8H7SM/2mbMtfKz4hFbUysoK/vHoiXRUz+fyhuSGBnF35jZ6ujvMC4PoLqu7fagDA8e6tLaJ//zP/0JHexv29/fx8MF93L1z2/S7u4BamtWdmZ69XhBQoquXlazRefimdr4QHd1VJLrV7Dr+87+/E6LLHe3iyy+/xMz0lLi24jG6L1lY2DXyd5sQV6Pzu6hhvS8NIhpzLDdoFYsXyK5m8fTpU6xt7SKdSotrsLOrAw8/f4DOjnb4Ad3EMcRw/sLMleZ4cuxR8n766i3+/ve/o72tFYeHh/inr7/CxPiosUxvyNpWwk9/X30ElOiqj/GNvoKt2EjrwmQox6WC/r//57dw/QClYg7Dw0P45uuvkEmlJJ5ENycrDMcTCYkj1fMWTYF434PfqipLpZLgwX2Wl1fx6MlvyOfzzB5ALneEvv4e3P/sLnp7u8MYHsJcwupadK7nI0FBC7u8e9LaVdyUsgXAtz/8FUtLy8xnEGv9//3ff0NnR1s9L6nOrQYRUKKrwUWppyFJAncooDDziiGXL+CHv/5DmqQmk6YtzMMvPherrqxF8cPjYvUtVjgZi/v92vvShYAExyar2ey6iE+Ws1nTaNUDWpqb8NlnMxgaHIATo6qS5JMIe8pV16JjZRpbRqxU8oTkWIotny8im83ip0ePpURbPneEwcFB/Nu//jOSCXYvr+91rae/4XqYixJdPaxiDc8h6rq0RMeH49z8Ev7xy69IpeISu+ns6JASVf293Uglk0J44sqssvy9VqCLCjqirj9atyQQWkNb27v4x8+/SHfwVDotuLU2NeHB/XsYGupnG2UhEQSsfxn2qavyi0LYJEGMda4XSY/ERivu5cuX2N4/DItMx6TO5u2p8VCcpERXK/feTRiHEt1NWOUrnONxsxlaJiy8THekg1yhiO9//F9ks8tobm7G0eEhmpqaMDY8hI6ODrFSqC88Q3bBFc727Je2lh2tNJIav6QJqluEE0tge3sbz56/lC7hdBcyfkkF68N7d6QTQSqVQKFwJOITEk4+xxhnAnAo/a+e+5cRWDa+tWKZo6NDrK2tI5tdw8HBvihrj3I5SR/5p3/6Bo3ptMRhdVMELhMBJbrLRPtGX8skKtu8OD56Nza38f2PfwXrVbKfGh/yDRnTS40WC6t5eF7po6hd9xgeXYyuWxL3Ltvq9HZ3Y2bmFjKZjAlz+S6OciU8+u03zM4tIJXOiCI1k06JBTw2PCAvEOlMGoVCEa/fzCK7toEgcODEmKfmVvWuizlxWT+6S7mmnANjh1RckoyLuUP09vVKrc1Bulb5X8hzVkFa1QHqyRUBvjIH9V71Vpe5phGYW85ibm4OS0tLYomwigc3/nwzLDoTi2ReWU9XJ25NT6OvrxfpFLsLBGINPXv2AvPLq8gXXdmvuTEj8czpyXEkEw4EKgBvZufw2/MXEgOlRShFnatsPXGMUkQ7rLRC8uIXN3421NuJkZERic9JTDFsL2FVpDehek1N/wHekMEp0d2Qha7VaRb9ADs7u1hcWsZaNoujoyMhObrDxNUZ/7ibSyqEXOONLXQ4z7a2Nvzhi8/R3d0lPfUY68odHeHZy9eYm18Q8qIrMplMYGpiDLenJ9GQTklaAd2H8/PzePLbM+TyeSRp9QmGTNeosurSLYni0iSxG9KjVd7S0iJFpe9MT6C5qUl65XGLFt6+CUW3r/GtWVdDV6Krq+W8fpMpeJ48jPP5Anb39rG9vSNNQ+nOo0VSSZx33dV7tHKYXzYxNobhoQERdQjJ5fKYnZ3FkxdvhPiKhTwaMincuX0L46MjaGxIwyfJxBOC3atXr7C5tSOESYHIwVEOqXTquEFflW6NqEVG4qIlyZgr46yZdBKtTY1htZvjcmPXfc2qBKWetooIKNFVEVw9dWUE8qWS5GHxgUkrjoo9WjjmixZC5XNc5z1isbiQOsU3nG8yGZf42q+Pn2BxcQG5UoBiPictdqbGxzA1MY6WlkYhMMbFnDhdlK6QJfEjudEidvkCEee5qidEMbhLgbewu7tJAid5JxKmwk0ibprCWhenXSu15q7zXXv9xq5Ed/3WrK5GLE1AHXYIN+4vQ3CmjqNpDFrtB/XVwklCIjEUi6Vy4eVXUr/ytbhx48m0WHPTE2O499ldseoYdjNCExPLJGnYclpMLDeuz7i4Eqvt2DWqWkeaufJn2/SW/EqhkG2AG0X5OhXdvtq7Q69+UQgo0V0UknqeMyJgRCcs+cXUA25RuXol1+UZL1ozh1nlobXA3rx5i58fPRbyIumTtMZGhjE1OSYVRUgchr5icOnmDLtC2BcDcwwtrLANzyUB+L48wA9Zbeq6rJnb78YMRInuxix1bU5UCg+zfBTdcFL82XQw4CYVw6ptklwxLGWVouNgcXEJvz17jv2Dw5CogKGBfty9cwttrS2IBT4cKYQck/Y80uDBp7LymNQMdjSnjLvQWn6XNc1KlV6iJKfpBZe1KnodJTq9B64YgXddk4bc6ovd6E60LWnoTvR8V0p0UXHJYpVBLIaV7KZUPWHDVM6fuXJDQ0P44rMZtJLk6K8sMz+tunAL2+GYFwMr+Ah/K37F2sVS43RX/Kd3gy6vRHeDFlunevkI8GFuk6elMHMyEbYrMoTu+D6Wl9lu5ymKrAlZdBFzAowMDWJ8YgJDvd21zFWXD6heURE4AwJKdGcATQ9RBE6LQNSa48/sscet5JaQTCSRXd/AT//4Cdt7+6JUZJWRjrY2fPP1H9Da3GRqV+qmCCgC50JAie5c8OnBisDHEaD0n5utCkIhCb2JJdfD7s4Ofvr1idSxlJZEvi+5Z3/8+it0d3WEqtPadT3q2isC1wUBJbrrslI6zmuJQNR1STUpBSTxuIPt7T08evQYKxubYC6d75XQ1tyIz+/fQ39fD2Ls2uC5cBKmJJpuioAicHYElOjOjp0eqQicAgGTaWZk/+yYHmBjYxsvX76W+p5+IglKS5LxGB4++AzjYyNi8UkyOGN4YcrFKS6kuygCisAHEFCi01tDEagiAkyfYKUTEh2Vl6S9Fy/e4OnTZ2DMzmNtyHQSD+7dw1B/t3Qh4MYKMYznXfdanlWEVk+tCJwaASW6U0OlOyoCn44AiY7F/E2/tph0Gtjd3Zc6lq9fvUEik8Tdu3ek8gk7ETgB29048BGTlkZ1XgHt0wHVIxSBMyCgRHcG0PQQReD0CDBx2+wtydRMig+AnZ0dcV2mGzLo7+9HixQ/NlnyUrqL+4Vl0U5/Ld1TEVAE3oeAEp3eF4pAFRGIJkVHK4FQjclaltGO4nYYmkhdxQXRU99IBJTobuSy66QvCwHG5kxx6tCik2IlpqJ/tDdbvVWDuSx89TqKwGkQUKI7DUq6jyJwRgROEp216k4SW7SdjpLeGcHWwxSBDyCgRKe3hiJQRQSibshoX7b3/WwEK8cJ4urCrOLC6KlvFAJKdDdquXWyV4HAh/qvWdelHZNaclexOnrNm4CAEt1NWGWd45UioI1GrxR+vbgiACU6vQkUgUtEoFIsrtLvL3GoeilFoG4QUKKrm6W8qomEDT6laSqkAggbgZbdcCe6p77TmJMHnOinxo9smIr92lg262Scy577Ihp32nOfjIeVP2dxSmlgyry2aM+3d3/+FPQ/FntT6+9TkNR9FYHTIaBEdzqcdK8PIGBKXAWIhTUZ3yUl4Ybwf++eIFrs+PenNhnW0URrK9SIkttFEF302lHSK6sjTb/uSNdz29z07ESnN5MioAhcLgJKdJeLd91djURnrLDjvmnGKmGuGD83xGBVhlFlYVR6f5Jw3vdvWorVVCJaa8p+t9cz8zNqSLW46u4W1gndAASU6G7AIld3in5IAIYI3pXHG2vOCuZZDYS/jyZQf0xpGLWwfn/uY8vqPPM7SVzRJG4hthMnt3OpJuGeZz56rCKgCPweASU6vSvOhQAtOpKV5xnioRXEzfN8xOMxuFIZhJ850nqGW0yso9BCek9fUd8zFiFP5fvvVhaxxPgha/Ask4m6QKPn5c9BLG7a5nh0z5qmqRwy58u+cropAopA7SOgRFf7a1TTI/R9V8jtuEK/g3w+j729fSlM7AYuUskkGjINaMhkjMUn+g7W6AcC4UVDGGxMms8XcHSUKxNJOhVHS0uLHEeLkLUhzb5+mVTPC1CU3HgNa3EeHBzgoFCQ6wSej4Z0Bq2tzcdEF4uYq+cdhB6vCCgCVUNAia5q0N6ME1uiA47jZxsbG1hZyQqZeY4hpPbWVvT19CKTyRh/IJmRBOl4cGDie8Wii62tbfkqFIpCON1drRgYGJBzFItFpFKpMtGdrCRyVsSjBGpJj59xHovZLOIk1yBAe2s7RoYGkaCl6vryveyXPevF9ThFQBGoOgJKdFWHuL4v4HklISQ2FzXqyxjW1tawtLQiVheJjg1GW5ubMTI0jPb2dsAPTAfteBweXMQcY6WVSh7W1jawvr4hVmEymUJnRxMmJibEouN52LzUWnT8bl2l50H55Hl5ThLdysoK5lazSMYTws1dHR2YHBtFXKzLAImEWnTnwV2PVQQuCwElustCuk6v4wUu4g6tOUcIzInHsL6xhbfz85J75rG7tusimYihva1NLKJMKgWvVEJcOm6zK2kMJbckhLe+vomFpaWws7aDzs4mTIwbovM81+SzkeAY8yvH+34P7rHI5N3f/T4nLya5f4asjxWiPGpxcRFLa5uIyfx8IbqpiVGjIpVmqsbrelKYwvNxe5/oppL4JTraD4lxouc/rQv3ZEzzQ8eZ8UVTKI4FRidzJD8mFuI8Ppb8btNLYmFnB5tLcpx/ifBlSFvP1umj41KnpUR3qXDX38V8eEI64rr0aKWR6HbwZu4t+BDzg5gRn5AZ4KO/pxuDA/3SOZsNRuOJuBCW67mIxxJYW9vE7PwcEvGkEFBfbweGh4eOicj6Csmrvo9EzLg97cPfujOP0wEM6djt90WT4+V4n3342+8LCwtYWdsyQhr46GrvwNSkIbqyHDMkumhXgiiZcVzvinTeTaiP7kvLkhvjkDYlI5rWwGtYQha3sOe9s2+UcKPH8We6fWkNW8Kzx75fPWq0pqWSib9awj7ZicFa2TZual5GjucXnRvHbv8dfQEw/dQduUfsWET5Gq6zwzioborAORFQojsngDf98EpEF5DoqFYMAhRLBaQTCUxOjKO9rVWsOD70aKX5gS+WE4nuzdwx0Q30d2JwkHEx494USyFkGcnNoxVJD2JYmUV2EF41JhdJWHiJ+4au1XfXzDk70fGccu3jPEF7jQ/lDkaJhQ90Erxxx5px0LIRcQ8CcZ+mkyYmGSVzSxQkr3gyIaRQJkaZvyN4+iQdxxCVTZuw4ztpnZ1Mq+BpZDyhe1gUqHwxCS3f6Od2PPaYaHK/53vywiPEFVbJOcaGlW9MnNORnEtDaiIIcmLlajQ3/W9M539+BJTozo/hjT5DRaIj34RuLGo3PNdDV1cHRkeGJe1ArJRE4h2L7u3CvFh0fODRohsdHQndh2HFFATyb3mwskyYkAStOtcQGt2GsRgSCWPtHbvDjrPiopbdSUuukkVnuNSkSwR8IAvZHZPp8YOeVpeLQqEgBEEhTtRSE6sstNKYjhElFr4ciMXKOGbEtWoJyShdQ/+pA7glX67FjRYWsbXKVhtz5BhoNVLQEyV+nkeuFSpai8WS/JsEbMqwHcdf35feYa01eWk5kVhPq52fcahMFTFzZC4lCfhEqbhIU1oSXzmX40b/henkLwIBJbqLQPEGn6MS0fne8QOT7/XmQQ1xX/b29pgHKRWVpaKQG2N080tL8nOxUERPT2s5RkfrR+pohhYMH9qHhznwwcy0hFKpKKRAK4EP83Q6hXRDUgiGqQF2EyFMpPfbx4huObtlHvQR16UlOlpMmzt7ODo6EtJraW1BU1OzPNAPDw+Ry+UR+B7yhbxYpPx9Y2MjGhoaxMrldnCQw+HhAQ4Pj8qWJQmjqanJ7JshKRmXJbdo3Is/b23vCcFx/iRUfkYRT0NDRjBgOgQ/39/fF+uXOPf09MgYzKyM69CcG8gd5bC7tyeY8mWiWMoLAfJcLc0tyDRk5Hx7e3vldI/W1lbBmGtjciSNW5pz3N7muYqiouX6WKLm+fjV3Nwg5xTBT1jzrewa5r/VdXmDny4XN3UluovD8kaeqRLRBa6L9vYOeXvf2zUPR25NTY1iqTU1ZuTNXUhMxCgbWFhelngdH6i9PW1loqOrU+JXMDGnza1N7O4diZXCL+bhiWOTz8cYE87jSGbi8oDubO9Ac2OjEZDYB2pYtuXjRLcpxPk+oqPI5s3cInZ2duQBTgJhzh/Hzc/4nekX3IQEYjH5fV9fH5LJBPb3D7C9uwfm63E+xhIzbkaSAIluoLfLkNKJPEJLNqvrW0IQnDsJ79jiiwvmQwP9QrocD18C+DU+Po6urk7BwvNNbJT4b23uhOMuyX7GsjOY07rj2JubmwXr3d1dGTN/np6eRnt7q6RcJJOGkAuFEo6ODrG6tolisVBedyFBedEwFndDJoGuri50dXSafEXrYpa1UVXrjXyoVGHSSnRVAPUmnbIS0UFclV3ytby8LA/IdDqNkuuiu6cbQ/09SKXT4du8g2yWRDEBLx8AABltSURBVLckD18+SPv7KEahm9OoIsXKKBaxvbMtaQyenxBLQcqLRYQT9F/yOekGxlXX1tqK7s4utDQ1IR5aCaKclOorJtfvfWKU5awhOgaROtvaRYwi44BJYH/y7BXy+Zy442iFcZy5XE4IgAQRixnXnSEOIwghFvzd9vY28iXjzovG2WgRWhFIf0+HxCj5b5IbseO51tfXsbW1haOCcTvS6iurUCNJ+W0tjTIWHmvJcnJyUoiO5BiL+UJQO7s7WFnOSrJ+MpmW8ZmXEiOmseXbLOnynMSB571z544QHdNDSHR8j1hbW5c8xJLHfWhpM9k/WSZyvpAwdueVjkCLsLe7B21tbXJdwYPrF3aMuEl/TzrX6iCgRFcdXG/MWSsRneN5QgC3bk1hfX0LS0tLSDdksLe/L5bK2FA/WtvbjCgFDlZW1jG/tIhkIiUPaBIdH/TJhMmfo7iBD9DNzU2xVJxYpiwyofuMD0oSAfPwhGwa4igVikIUJLr+3j40NaSNe80NEEt8XIxSiegeP31Ztlai8SmSK8dDi44uTONSNa7HeJwEGDME7dO6bRIC5JhJhtatymPSiQC3b98W687G6midUREqVqyTCs/tyDlIhFYNSRKirIWbVX7yM+Yl9vR0htVnAmxsbiGbzSKfK5rEDcdYn+xIkUoZy5BkRUK3liljimIReh4mJ6fQ0dFWTkvY2dnD0tKyzMeJG8Kk67axqVHGyDnyd6L8jDPPsoiWpmZ5oSHpiVXn+UKEmpB/Yx4lVZ2oEl1V4a3/k1ciOj6w+JD+7M403JKLubkFHNLiofgiCNCYSWF0bBTNTYwZOVhb28L84oJYGxRi9Ha3YWBw2FQhASSWRVWmWChwkMsdob+vD60tLchkGsoWQZ6xpt1d7OUOTZWVREIsioG+XklxEKuJcbr3WHJRMYoQXcyIMbra2zA1OW5co7TSXBePX7ySuJaxRDxRl/Z0d0tiPN2TTKg/yuWxsbGFA1pLqaSMm6TR0tQoBEGiS6XS8vDP54uSNF8oFgwplAqYnBxHT3eXWJEkh7m5eWzt7Jok/VDV2NHeLiTB2Bw3kiCvIecK0xYYuysU8hgfHUFvb7cRCTnAsxevsL+3j0zKxN9IbN09tH6bEU/EZB24Hjs7u9je2RHLzW6u72NqagId7a2SSM/rzs0vYWNrW15OPLcgLzTd3V1obmlBPGbENXTX0iInyRFbEmF7RzvGx0z6BrGVijS6KQIXgIAS3QWAeJNPUZHoAqC5qREz05PiMpS3/eVVHFE4wQet76G/vx+dnR1obEhjbX0L80w2D0UNfV3tGBoeLRdUplhldn5BIBcrMChhdHQUrc0tQgy2Uorv8mF6iJW1NeweHBoLim7Uzg6MU/EZ4/Em/++jrsu1DROje4fomPdFBamLxy9fi2XJep7ME8wkUxgeGkJbm6nPicBDseTJnFfXN5BMpQUHujcHenvQ39clrtV4qDJ1vQBv3rwVIuDnR4U8hocHMTTQJ5J7kuGr12+QK7pg8esYPCHV3t5eiXvyhcDE7KjC9LC2vonNnV0ZI6/tuSVMjo+hp6uD0iDs50t4+fK1qToj7uICurs7MTDYh8aMdSmbNkwkQRYD2NzcLscUS74nRNfZ3ipEzHG/nVvAPsk/nkQq4aCjox39/YxLGqvcELEr7teVldWyFc753r1zW9bVlmWLqmNv8t+Zzv18CCjRnQ+/G390RaLzArR3tEnprEScFomP1ey6EJDnUnEJeaB3dHRgaLBPiO7t27diBZAMBnu7MTLKuJghptnZOaxtbpUJrbuzDQMD/ZJvZl1+RlZvrB9aPvNLy/IziY6kOzU+JqRqiqycj+ge0aLL8aEel/P1dZO8espSfZIfLa/s2oaMw2GCO3MGYzHBpK2VAhnmwRlLhxbm3NySxO+4FdwS+vt7MTI0IMnxdFu+mZ2Dz4LZJQ/pZExckc3NjA+a1H0bH+Tx+UIJiyurQiqxOIU8AaYnxtHV2S4kvLq5g/n5RRmPWywhnUoJcTU1N4DvAVYcYlyajpyP+3N8XDcS3cTEGLo72yWuRrcySb3gemIuNjSkRcTCFxlu1jVLoRCJc2lhPnTjluT7Z3dnxAPw/pzHG//npgCcEQElujMCp4cZBCoRXanAOFsvxkeHyjJ5uucWl1clNkTXGB9qfLgxkXx7Z1eIjuo+WgfD/T1CdEy/ItE9fvwbjgpGoci3/vGxIXR3dYm1YzeJZYUVU/LFEp48ey4Wjuv5SCUTQnRt7EIgyVrnI7pfnr0wD2+xMB3cmpyScxthp1SvFhLb3tnDq9m3rJIG33PFXXnn1jRSSZtyEVZoicexsLAihCEqSQTiZhwbGZI5krBm384jnkqjVHTR0pTBzMwtk9nHXn+x45qgUi3GiWNheUWO41sFr02C7enulLEtZTfEnUzScgslsb6mpsbhBx5SiWiieZiUDgdLS6tSB5SWF8c3Pj6Kns4OSVCn4IhWJBibK3myvtzP5u7ZRHU5lgKdXE4I2opb7szcEhes3FsX2KFC/15vNgJKdDd7/c89+0pERyuhp6vLqBVFwOBI14K9/SPMzs9LjI0PQT7UKDrhw48PS35GAhno6cLI6IhYRbSYfv75VxTD3Dz+/tbUODo7OiRlwLq55AFpK43EY/j50W/GlccqKqFF00nxBLujOx8vAbZcwXX502/PjCJRBB8B7t/9TKxFo2h04HslOLEEdvcO8OL1G1PXs1gQheFnM9OIOaZiC8lQ1IaxGBYXjQVGLHwH6OnpKhMdRSMkulRDoxBda3ODEB2Vk5w/a4pa0YpYdskkFpazZaJzS0Vx3ZoYnQ/Ob3Z23qg5i66oMScnR6VqTTppctuMatR85/goGOIayecniI4imY3NbcSSKRmfmHkhadlzWQUt58sCcFbxyt9PT02IK9amWVxE0e5z3+R6gmuPgBLdtV/Cq51AJaKjljKTSeHuzC155klSMAkggLjz5haMNUHSolVHpSKTkW0+WG9nG0bHxsJ+d8DTp89wmGcSs1HvTU+Noauz0z5PI6WwSDIezSz8+uSpnI+uS8YEb09N4qKIzlp0poJJCZ/fuy9J3mEXIgS+y0c59g+O8OzlKyRCQQgLXDNuGXOsKtKkT1DKaC06/rvouejr6xGiI3mTAOm6TKQz4vo1Ft1tuQnkHSJMZSiX/YrFML+0itXV1bLbdGJ0xFh0gYeF1XXpNCFrkC9I4e3btyelzJrtK2sqp4RFqh1HXKs8H8mR46PrMmrRZdfWEcQSUt6UFh3X1Vpw9m61pOf4x8IWEvTgQJ9Y89F43tXe4Xr1ekBAia4eVvEK51CR6AKIhTNz+5bE44xPz9Q3zOVdKeBMoYTN07LWHa0RPhx7OloxNk6lo3Hx0WJY39oWK4APxoG+LhGzMEYXrRpiayvuHR6JJSWSe5cuTUeIju7Fi7DoKEZhZRSO23OLePDZPWTSpj6l0dMYkjg4zIkLNdPQiHzuSKyW6ckJxB3zoKeU31p0b98uSo6c5Km5JQwNDWB4sF9cl4zRvXo9K53PGQPLpOKSAN7S0mTuglCIYiupUNzydn4B2bU1JNnLLwhAouumGMUJsJzdwOLSiknWdpmonsT09AQaG6mCNSTMteH4JJevWMLbtwsSoyPRFUpFTE5NSIyOby/Sw29pRWJ0TBFJpxKyPk1NDWLlSsyvXBIurH8Z3r+M35rY6XEh6Su8tfXSdYSAEl0dLeZVTKUS0ZXyBQz292JsdASuZxKmpa24VOUAdvYP8OaNISI+BKWQMS2FInO6AKouSXQmN8yT/DmKK8wzPUA66YAJ0JTC289sYjktuvnFJSyuZsVSpOuSJESik9JaPpPMDcF8MGG8guvyyas3YoGyezpz5kh0aaYQlNv3UAFpiO7x02doaGzC0eEBOjs7RRSSiBvXnhWjMHeMFpMlulyxgLGxEQz194m1xpeCl6/eiPs25lB16kpFFgpyWGlECjmzTFqI59b2Lpaza1ICjCRL1+XI4AB6e7okprhzkMOLF6/kpaEhxTl44irt6+9FKoyfRsfH8zFlgQIcWa/AlxxJq7okFnSt0upuyDQhcPMYGxtDW1urEJzU07Qd5h1gZTUrLzQUrNBKTyWPa3texf2s16xPBJTo6nNdL21WARifoqAkLE4fi2GDbXpmZ+UBVirljRhlbCysjsHcKPMmz7iS7zgS76GFYBqgUmofl9qNQnQSoxsOCwMHkjIwJ7E9NmZNSIUVVhqhhUSXFx+UJddH7uhIcu5W15mrxTJXJhGa+V6SXsCC0pKUfNwZ3cryLVHQelxc25B8MI6th/Gr8VFT0FmUncA/fnsqLj8SOIUeX9y/HxaUjpkHOl2TgSMxuucvXkkVmFKxKIIL5uTF40wkt6IPJkg7WFhcweoKO5vHZd/BwQGMDA+E+WWeEAnz2ahcpGgknc4Icba3t4lFRJLL5YuCwXI2i0K+IEQmeXlMGB8dE6LjmvlOgNev3wixZtKmXiXxpwqWSslMJikuSKorSZZM7zg6yotrU1yaDjA9OS4d5BMxSH3SuXkTp8s0NsMtmXgk46gtra2yPrwu1/Eol8Pq2pqQM3MgOzva0d3ZiQS7Xdief6aimG6KwLkQUKI7F3x6MEtE2fIV0nzVcbC5aZSTrABSKB6ip6cbk+MTplOBbXBqq//HYkJIVPHRLWddZLY3G6X17EdnhSZ8YK+uZsWyk1qSUjMxIVYgY0FUVdJyo8XBr1giLgndJCYmVQ8P9KOlucmUByt6SKSOG65yNaNKvyjRmbqbPZgaZycFlsRi2S7g1+fPUSqWyknODx/cl9+ThAMvgB8zNTz39g7w6tVrmZ/rlgzRTU0gnghTIXy6VZPiLFxazmJ1ZVVI3ysxr60Lo6PDobKSEv4tyT9jLclkpqFcGcUUjDZkRXInhvuH+2VSTlKpWihhcmJCOkiwMgwSAbKr6xJzsyXK6FomKVIZanK2Y+JCpYvWlBIzrZWIKbsvTE6Oobu9XYQ1ZDHG6JaXsyhJ7VFTlYUWNa22JK3OIJA1l+oogaliQ9fvQF8/eru6heikxZKIX/RvTBE4PwJKdOfH8IafwcRxpDkpn3NwsLGxLUnffODmCwfSpWBqYqqcGyVkYtvswDwsd7Z35WEric1hrUU+qPlAHhkZETebFXjkcgWpqsF4EGNVptaj6ZVmY1OSThBW1+DDmSQwMjgoIhTT5NNYWu+0sQuT1Dkbno9Et8wO42F7GyZ4j48ZopOHfMnD45ev5OEvfeQAPLh/T8jWJIuzX50pqHmwfySJ2dY9a2T8TKI3aklP6njGhaSXV9cEC3kpcEtirVHCb1MsSGKsJcl9OH8bmzS1NU26hJXrpxtMiTBWpUmyKonrhkTXyfAhghhrUZakBBjxNMRkMBU3o0OLPY5CsQgv8MMuBaYOKWmM56ZSkmIUG9Nj+ghzJenmZAVO7sMxkjzti44oSrlGvsmfa29rx1D/ABobMmFbJ7Za0qLON/zhcmHTV6K7MChv5okCSvQlh8u8ejPutrGxiYWFxfCNnxZJN6YmJstv9zahmx+4gYkp8UG8spKVBy7PRWuGFsTgUJ8QHclFWr+E36Ui//a25KeR0PjwN2RnXJTkGSFAJyYus96uLhGgiFw9TNiOVt2IWnJCYmI5rmJxdd0IX6TuZi9GRkw5MlFEFot49OyluAOpUKTFNDMzI/G/ciV+x4hRDg9yePXqTfmhzyLIFJEkExSimC7rxJEy/tVsFivZNWNdBr64EVkGjBaz7X1HMiFWdGEa0jANaO0mOXXxBLp6upDL53FIJatnqqXQjUwrke5cD+alY3//UIiO1hVfJDg3WmElNyeWJo9jO52WtjZxK7McGFMXiP0kVZfshhB4hqQQE9cpLc+dXeOStl0rrPVvukvEJMZH0u/t6hFLW5r0hpoljpeqTd0UgfMioER3XgRv+PG2cka59FYAaT+Tza6FFfU9cVkN9g+8W+3CSO+OO3SzjuXBobi93BLf8uPSx41VRrq6u40VJUEv0+uMGx+g29umXYztGMDPbZyJ3xsaGyV+Z9V8xx3JjxOrhaDD5qbWmiPJMG64sWViYSydRcKRmpNh9wM+vOcXl40qUYgljoH+PlEuHsv7DdHRalpaXAY7rtOUYrmuXlZQCYnZ3kb09m1v72BreyfstB1IlRi6b8lkdvwkDJLSzu5e2U1ryYSWE4+hO7e9sx35XO64TY/ror+vX9ZEErXZVSDOmpy+EBhxJOnxRcKkBBREPcm6k4y1ZRoasLxq8vIYEy2WShgbHUZfd5dYdEYMkxTiphVIQqTFawtW2xcK2+OusalB3LiMD0p3vDBH0qwJXd1KdDf8EXMh01eiuxAYb/ZJog8k686iYEEEBbQYYg6aG5vK9QsFLdvs2zHWE60PPgRNSxceYywy26AzSkRRlSSrnVg3pcuyU5FK/bx+KmV6qZEgaCrYxqAcgBW/nCQ6S3Z8QNOtShuD16Fik7E3YwlSKu9LSSx7bl6AiksjZjHuT8cxJcD4dXBwJMpIU84sJo1hy01Py+kIQLHkhr3gfKnJybnbqv52fnaMLt2SrhdatMa65vV5HenHF1Y3ofBDyJfqyoYGUyc0tI55jOktZxrbcr1ImoWCKxan7bYg6QlwJL1BiK61RbAfGxmW2pmSSsEyZohLUQApR+a5sp48n+2ibjspcIx080pB7PDlhQ1s7ctKdK43+y9MZ39eBJTozougHi+yfz60uNnO0saVZgjBD3yp08iHKYnrXaIz8TVTScQ8fPlA5Gbe5vnzu9aXYUnuR3clUxVY+ur3b/5lV2c5hmf2Mf3erJ/PSPFPui6tPP9YBGOsCzNWt1x4OB43+XvGpWjLeRkWNwngfPhTVs+2Q6ZfmxlD2OVcRDmhnseSo3RLMG8DRvjCXm5hu5uwon90vORwsfRCt58hCAOzfUGw57CJ2vZ4xt3YcJVpAdyXViALRDPJX9ZBupubLgJ8MdjbPxAXsxSyTqeRSCWlpBi7T0i6hsQvYxJrFNdomBBO8crxS0bkPSeM4RlX63EXdUkRec+a6p+bInAWBJTozoKaHvMOAtGGm3zoShgsfEOXfDlK2+NskMr0gbCCfWjRBWFjT6nLCCNttzEyPtwZA4wSER/Q3MoxMHEFmo7i7ySMywM35NQwFYBEYAjouBqHrfhhCcA+0DkOuQa1JCQgElNIdDy+nHfnJCT2JUTHlAUhMEPy9mdzDaYoHDcmFdmOqBRNGoKMK8yfts93WkO0i2y6g228yn0tcRk8TOzOfrc4GIl+WMKL7tXQuot2B+A1Xr+aldQBSZHwGTPrEqUsXbBGYBKT67Ht0ebWlrhhLVm3dXZgYtTELYuFnLQbkvqhLBnGNSmb7r8nLnkPiJA+95UyY6HYxxB2JPCof3eKwBkRUKI7I3B62DECtq6jIZGQGI59k0IS0YTsd7Gz1o/51D7YLPFYa8keE32Ih0eUT/f7331old5/Tbt32doKO3WX1RHlh671uxpysTl1EkMLrbvolQ0mJD5T/9JiZC3T3+9rPnlnHO+JI36MEKLELesS1tG0lpz9PeX9y8ur2NrcDPvM0d2bEctOKq9kTK6iFZQUi6V3xjUzMy3xRtIRLWxjlZGxw1mFPHVyPO9bmZPrd5pj9O9QETgNAkp0p0FJ91EE6hQBxlAPDo9Ecbm7sy/WGlWrJoZHty5TA4zFzM2mLTQ1NYs4ha2V1Oqq05ujjqalRFdHi6lTUQQ+FQESHVMacvmcEN3u7p6oLw250WXJn43b0QpYGGdlbh8rp1B8o5siUOsIKNHV+grp+BSBKiJgYmjMUfSlfxxLq1FoQtWsEQ8lTAUa3xe1JtMSmHxPxaiJ4emmCNQ+Akp0tb9GOkJFoKoIiLT/OLgK13OF9JgjR5GJEQpBxCq05liDUwmuqkuiJ79gBJToLhhQPZ0icN0QiKpVOfaoICiaxmCVpFYkY9Wg122+Ot6bh4AS3c1bc52xIlBG4HfqTFarCb+s1D+q7uSBUXWkClH0ZroOCCjRXYdV0jEqAlVE4CSxScFrqfxC684k1EcJLmr1VXFYempF4MIQUKK7MCj1RIrA9UXg3Ry2d/MEr++sdOSKgEFAiU7vBEVAEVAEFIG6RkCJrq6XVyenCCgCioAioESn94AioAgoAopAXSOgRFfXy6uTUwQUAUVAEVCi03tAEVAEFAFFoK4RUKKr6+XVySkCioAioAgo0ek9oAgoAoqAIlDXCCjR1fXy6uQUAUVAEVAElOj0HlAEFAFFQBGoawSU6Op6eXVyioAioAgoAkp0eg8oAoqAIqAI1DUCSnR1vbw6OUVAEVAEFAElOr0HFAFFQBFQBOoaASW6ul5enZwioAgoAoqAEp3eA4qAIqAIKAJ1jYASXV0vr05OEVAEFAFFQIlO7wFFQBFQBBSBukZAia6ul1cnpwgoAoqAIqBEp/eAIqAIKAKKQF0joERX18urk1MEFAFFQBFQotN7QBFQBBQBRaCuEVCiq+vl1ckpAoqAIqAIKNHpPaAIKAKKgCJQ1wgo0dX18urkFAFFQBFQBJTo9B5QBBQBRUARqGsElOjqenl1coqAIqAIKAJKdHoPKAKKgCKgCNQ1Akp0db28OjlFQBFQBBQBJTq9BxQBRUARUATqGgElurpeXp2cIqAIKAKKgBKd3gOKgCKgCCgCdY3A/wcG5tBSb8nfsgAAAABJRU5ErkJggg==";
#pragma endregion

void on_ok_button_clicked(GtkWidget *widget, gpointer data);
void on_parse_button_clicked(GtkWidget *widget, gpointer data);
GString* run_command(const char *command, GtkWidget *widget);
int database_handle(gchar* database_name, gchar* collection_name, bson_t *doc);
void update_log_text(GtkWidget *text_view, const gchar *new_log);
void enqueue_command(const char *command);
GtkWidget* create_log_dialog(GtkWidget *parent);
bool check_if_document_exists(const char *database_name, const char *collection_name, const char *id_str);
void show_message_box(GtkWidget *parent, const gchar *command);
int convert_to_seconds(const char *duration);
GtkWidget* fetch_grid_elements(GtkWidget *widget, gpointer data);
static void activate(GtkApplication *app, gpointer user_data);

int main(int argc, char **argv) {
    if (argc > 1 && strcmp(argv[1], "command_line") == 0) {
        printf("CLI Not Implemented Yet");
        // Implement CLI : --history returns last 4, --upload youtube_link, --media UID
        return 0;
    }

    GtkApplication *app;
    int status;

    mongoc_init();
    
    client = mongoc_client_new("mongodb://localhost:27020/");
    if (!client) {
        fprintf(stderr, "Failed to parse URI.\n");
        return EXIT_FAILURE;
    }

    app = gtk_application_new("com.example.Media_handler", G_APPLICATION_FLAGS_NONE);
    g_signal_connect(app, "activate", G_CALLBACK(activate), NULL);

    status = g_application_run(G_APPLICATION(app), 0, NULL);
    g_object_unref(app);

    mongoc_client_destroy(client);
    mongoc_cleanup();

    return status;
}

// Correct
void on_ok_button_clicked(GtkWidget *widget, gpointer data) {
    if (url == NULL && title == NULL && id == NULL && artist == NULL && thumbnail == NULL && duration == NULL) {
        show_message_box(gtk_widget_get_toplevel(widget), "Check The Values");
        exit(EXIT_FAILURE);
    }

    if(check_if_document_exists("media_server", "media_info", id)) {
        show_message_box(gtk_widget_get_toplevel(widget), "Entry Exists");
        exit(EXIT_FAILURE);
    }

    GtkWidget *window = (GtkWidget *)data;
    GtkWidget* song_entry = fetch_grid_elements(window, "song_entry");
    GtkWidget* artist_entry = fetch_grid_elements(window,  "artist_entry");
    GtkWidget* ok_button = fetch_grid_elements(window,  "ok_button");
    // Fetch All Widgets At Once

    title = gtk_entry_get_text(GTK_ENTRY(song_entry));
    artist = gtk_entry_get_text(GTK_ENTRY(artist_entry));

    GtkWidget *text_view = create_log_dialog(window);

    update_log_text(text_view, "Operations Started...\n");

    const char *video_path = g_strdup_printf("./../Videos/%s.mp4",id); 
    const char *audio_path = g_strdup_printf("./../Videos/%s.m4a",id);

    gchar command[512];
    snprintf(command, sizeof(command), "./yt-dlp -f 'bestvideo[ext=mp4]' -o '%s' --no-progress %s", video_path, url);
    GString *result = run_command(command, widget);
    if (result == NULL) {
        show_message_box(gtk_widget_get_toplevel(widget), "Video Download Failed");
        exit(EXIT_FAILURE);
    } else {
        update_log_text(text_view, "Video Download Complete\n");
    }

    gchar command1[512];
    snprintf(command1, sizeof(command1), "./yt-dlp -f 'bestaudio[ext=m4a]' -o '%s' --no-progress %s", audio_path, url);
    GString *result1 = run_command(command1, widget);
    if (result1 == NULL) {
        show_message_box(gtk_widget_get_toplevel(widget), "Audio Download Failed");
        exit(EXIT_FAILURE);
    } else {
        update_log_text(text_view, "Audio Download Complete\n");
    }

    bson_t *doc;

    struct stat st; 
    stat(video_path, &st);
    int video_size = st.st_size; 
    memset(&st, 0, sizeof(st));
    stat(audio_path, &st);
    int audio_size = st.st_size; 
    
    
    doc = bson_new();
    BSON_APPEND_UTF8(doc, "_id", id);
    BSON_APPEND_UTF8(doc, "song_title", title);
    BSON_APPEND_INT32(doc, "plays", 0);
    BSON_APPEND_INT32(doc, "video_size", video_size);
    BSON_APPEND_INT32(doc, "audio_size", audio_size);
    BSON_APPEND_UTF8(doc, "video_codec", video_codec);
    BSON_APPEND_UTF8(doc, "audio_codec", audio_codec);
    BSON_APPEND_UTF8(doc, "Format", video_format);

    if (!database_handle("media_server", "media_info", doc)) {
        update_log_text(text_view, "Media Info Updated\n");
    } else {
        show_message_box(gtk_widget_get_toplevel(widget), "media_info Upload Failed");
        exit(EXIT_FAILURE);
    }

    doc = bson_new();
    BSON_APPEND_UTF8(doc, "_id", id);
    BSON_APPEND_UTF8(doc, "song_title", title);
    BSON_APPEND_UTF8(doc, "artist", artist);
    BSON_APPEND_UTF8(doc, "youtube_link", url);
    BSON_APPEND_UTF8(doc, "duration", duration); 

    if (!database_handle("media_server", "media_metadata", doc)) {
        update_log_text(text_view, "Media Metadata Updated\n");
    } else {
        show_message_box(gtk_widget_get_toplevel(widget), "media_metadata Upload Failed");
        exit(EXIT_FAILURE);
    }

    update_log_text(text_view, "Press OK To Continue\n");
    gtk_dialog_run(GTK_DIALOG(gtk_widget_get_toplevel(text_view)));
    gtk_widget_destroy(gtk_widget_get_toplevel(text_view));

    enqueue_command(g_strdup_printf("./process_video.sh %s %d",id,convert_to_seconds(duration)));

    show_message_box(gtk_widget_get_toplevel(widget), "Successful");
    gtk_widget_set_sensitive(GTK_WIDGET(ok_button), FALSE);
}

// Correct
void on_parse_button_clicked(GtkWidget *widget, gpointer data) {
    GtkWidget *window = (GtkWidget *)data;

    // ./yt-dlp --print "title: %(title)s\nid: %(id)s\nartist: %(uploader)s\nthumbnail: %(thumbnail)s" https://www.youtube.com/watch?v=bB3-CUMERIU

    // curl -o ./.thumbnails/hello.jpg https://cdn3.pixelcut.app/7/20/uncrop_hero_bdf08a8ca6.jpg 

    GtkWidget* youtube_link = fetch_grid_elements(window, "youtube_link_entry");
    GtkWidget* song_entry = fetch_grid_elements(window, "song_entry");
    GtkWidget* artist_entry = fetch_grid_elements(window,  "artist_entry");
    GtkWidget* uid_entry = fetch_grid_elements(window, "uid_entry");
    GtkWidget* image_box = fetch_grid_elements(window, "image_box");
    GtkWidget* ok_button = fetch_grid_elements(window, "ok_button");
    // Fetch All Widgets At Once

    url = gtk_entry_get_text(GTK_ENTRY(youtube_link));

    gchar command[512];
    snprintf(command, sizeof(command), "./yt-dlp -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]' --print 'Title: %(title)s\nID: %(id)s\nArtist: %(uploader)s\nThumbnail: %(thumbnail)s\nVideo Extension: %(ext)s\nVideo Codec: %(vcodec)s\nAudio Codec: %(acodec)s\nFormat: %(format)s\nDuration: %(duration_string)s' %s", url);


    GString *result = run_command(command, widget);
    if (result == NULL) {
        show_message_box(gtk_widget_get_toplevel(widget), "Print Didn't Worked");
        exit(EXIT_FAILURE);
    }

    show_message_box(gtk_widget_get_toplevel(widget), result->str);

    GRegex *regex;
    GMatchInfo *match_info;

    const gchar *pattern = "Title: ([^\n]+)\nID: ([^\n]+)\nArtist: ([^\n]+)\nThumbnail: ([^\n]+)\nVideo Extension: ([^\n]+)\nVideo Codec: ([^\n]+)\nAudio Codec: ([^\n]+)\nFormat: ([^\n]+)\nDuration: ([^\n]+)";

    regex = g_regex_new(pattern, 0, 0, NULL);
    g_regex_match(regex, result->str, 0, &match_info);

    //g_free(command);
    //g_string_free(result, TRUE);    

    if (g_match_info_matches(match_info)) {
        title = g_match_info_fetch(match_info, 1);
        id = g_match_info_fetch(match_info, 2);
        artist = g_match_info_fetch(match_info, 3);
        thumbnail = g_match_info_fetch(match_info, 4);
        video_ext = g_match_info_fetch(match_info, 5);
        video_codec = g_match_info_fetch(match_info, 6);
        audio_codec = g_match_info_fetch(match_info, 7);
        video_format = g_match_info_fetch(match_info, 8);
        duration = g_match_info_fetch(match_info, 9);
    }   

    g_match_info_free(match_info);
    g_regex_unref(regex);

    const char* dot = strrchr(thumbnail, '.');

    gchar commandC[512];
    snprintf(commandC, sizeof(commandC), "curl -s -o ./../Thumbnails/%s%s %s", id, dot, thumbnail);

    GString *result1 = run_command(commandC, widget);
    if (result1 == NULL) {
        show_message_box(gtk_widget_get_toplevel(widget), "Thumbnail Download Unsucessful");
        exit(EXIT_FAILURE);
    }

    
    if(strcmp(dot,".jpg")!= 0) {
        gchar commandV[512];
        snprintf(commandV, sizeof(commandV), "convert ./../Thumbnails/%s%s ./../Thumbnails/%s.jpg", id, dot, id);
        GString *result2 = run_command(commandV, widget);
        if (result2 == NULL) {
            show_message_box(gtk_widget_get_toplevel(widget), "Thumbnail Did Not Convert");
            exit(EXIT_FAILURE);
        } else {
            if (remove(g_strdup_printf("./.thumbnails/%s%s", id, dot)) != 0) {
                show_message_box(gtk_widget_get_toplevel(widget), "Thumbnail Delete Failed, Do It Manually");
            }
        }
    }

    GdkPixbuf *pixbuf = gdk_pixbuf_new_from_file(g_strdup_printf("./../Thumbnails/%s.jpg", id), NULL);
    GdkPixbuf *scaled_pixbuf = gdk_pixbuf_scale_simple(pixbuf, 400, 250, GDK_INTERP_BILINEAR);
    gtk_image_set_from_pixbuf(GTK_IMAGE(image_box), scaled_pixbuf);

    gtk_entry_set_text(GTK_ENTRY(song_entry), title);
    gtk_entry_set_text(GTK_ENTRY(artist_entry), artist);
    gtk_entry_set_text(GTK_ENTRY(uid_entry), id);    

    gtk_widget_set_sensitive(GTK_WIDGET(ok_button), TRUE);
}

// Correct
GString* run_command(const char *command, GtkWidget *widget) {
    FILE *fp = popen(command, "r");
    if (fp == NULL) {
        show_message_box(gtk_widget_get_toplevel(widget), "Failed to run command\n");
        return NULL;
    }

    GString *output = g_string_new(NULL);
    char buffer[128];
    while (fgets(buffer, sizeof(buffer) - 1, fp) != NULL) {
        g_string_append(output, buffer);
    }
    pclose(fp);

    return output;
}

// Correct
int database_handle(gchar* database_name, gchar* collection_name, bson_t *doc) {
    mongoc_collection_t *collection;
    bson_error_t error;

    collection = mongoc_client_get_collection(client, database_name, collection_name);

    if (!mongoc_collection_insert_one(collection, doc, NULL, NULL, &error)) {
        show_message_box(NULL, "Mongo Insertion Failed");
        bson_destroy(doc);
        mongoc_collection_destroy(collection);
        mongoc_client_destroy(client);
        mongoc_cleanup();
        exit(EXIT_FAILURE);
    }

    bson_destroy(doc);
    mongoc_collection_destroy(collection);

    return 0;
}

// Correct
bool check_if_document_exists(const char *database_name, const char *collection_name, const char *id_str) { 
    mongoc_collection_t *collection = mongoc_client_get_collection(client, database_name, collection_name); 
    bson_t *query = BCON_NEW("_id", BCON_UTF8(id_str)); 
    mongoc_cursor_t *cursor = mongoc_collection_find_with_opts(collection, query, NULL, NULL); 
    const bson_t *doc; 
    bool exists = mongoc_cursor_next(cursor, &doc); 
    bson_error_t error; 
    if (mongoc_cursor_error(cursor, &error)) { 
        fprintf(stderr, "Cursor Error: %s\n", error.message); 
    } 
    mongoc_cursor_destroy(cursor); 
    bson_destroy(query); 
    mongoc_collection_destroy(collection); 
    return exists;
} 

// Correct
void show_message_box(GtkWidget *parent, const gchar *command) {
    GtkWidget *dialog = gtk_message_dialog_new(GTK_WINDOW(parent),
                                               GTK_DIALOG_DESTROY_WITH_PARENT,
                                               GTK_MESSAGE_INFO,
                                               GTK_BUTTONS_OK,
                                               "%s", command);

    gtk_dialog_run(GTK_DIALOG(dialog));
    gtk_widget_destroy(dialog);
}

// Correct
int convert_to_seconds(const char *duration) { 
    int minutes, seconds;
    if (sscanf(duration, "%d:%d", &minutes, &seconds) != 2) { 
        show_message_box(NULL, "Check The Duration, Only Minutes And Seconds Allowed");
        return -1; 
    } 
    int total_seconds = (minutes * 60) + seconds; 
    return total_seconds; 
} 

// Correct
void enqueue_command(const char *command) { 
    const char* QUEUE_FILE = "command_queue.txt"; 
    const char* LOCK_FILE = "command_queue.lock";
    int lock_fd = open(LOCK_FILE, O_CREAT | O_WRONLY, 0666); 
    if (lock_fd == -1) { 
        show_message_box(NULL,"Failed to open lock file"); 
        exit(EXIT_FAILURE); 
    } 

    struct flock lock; 
    memset(&lock, 0, sizeof(lock)); 
    lock.l_type = F_WRLCK; 
    lock.l_whence = SEEK_SET; 
    lock.l_start = 0; 
    lock.l_len = 0; 

    if (fcntl(lock_fd, F_SETLK, &lock) == -1) { 
        if (errno == EACCES || errno == EAGAIN) { 
            show_message_box(NULL, "Another process is holding the lock, try again later.\n"); 
        } else { 
            show_message_box(NULL, "Failed to acquire lock"); 
        } 
        close(lock_fd); 
        exit(EXIT_FAILURE); 
    } 
     
    FILE *queue_file = fopen(QUEUE_FILE, "a"); 
    if (queue_file == NULL) {
        show_message_box(NULL, "Failed to open queue file"); 
        lock.l_type = F_UNLCK; 
        fcntl(lock_fd, F_SETLK, &lock); 
        close(lock_fd); 
        exit(EXIT_FAILURE); 
    }

    fprintf(queue_file, "%s\n", command); 
    fclose(queue_file); 
    lock.l_type = F_UNLCK; 
    fcntl(lock_fd, F_SETLK, &lock); 
    close(lock_fd); 
}

// Correct
GtkWidget* create_log_dialog(GtkWidget *parent) {
    GtkWidget *dialog = gtk_dialog_new_with_buttons("Download",
                                                    GTK_WINDOW(parent),
                                                    GTK_DIALOG_DESTROY_WITH_PARENT,
                                                    "_OK",
                                                    GTK_RESPONSE_OK,
                                                    NULL);
    
    GtkWidget *content_area = gtk_dialog_get_content_area(GTK_DIALOG(dialog));
    GtkWidget *scrolled_window = gtk_scrolled_window_new(NULL, NULL);
    GtkWidget *text_view = gtk_text_view_new();

    gtk_container_add(GTK_CONTAINER(scrolled_window), text_view);
    gtk_container_add(GTK_CONTAINER(content_area), scrolled_window);

    gtk_text_view_set_editable(GTK_TEXT_VIEW(text_view), FALSE);
    gtk_widget_set_size_request(scrolled_window, 400, 300);
    gtk_widget_show_all(dialog);

    return text_view;  // Return the text view for updating logs
}

// Correct
void update_log_text(GtkWidget *text_view, const gchar *new_log) {
    GtkTextBuffer *buffer = gtk_text_view_get_buffer(GTK_TEXT_VIEW(text_view));
    GtkTextIter end;
    gtk_text_buffer_get_end_iter(buffer, &end);
    gtk_text_buffer_insert(buffer, &end, new_log, -1);
    while (gtk_events_pending()) gtk_main_iteration();
}

// Correct
GtkWidget* fetch_grid_elements(GtkWidget *widget, gpointer data) {
    if (GTK_IS_CONTAINER(widget)) {
        GList *children = gtk_container_get_children(GTK_CONTAINER(widget));
        for (GList *iter = children; iter != NULL; iter = g_list_next(iter)) {
            GtkWidget *result = fetch_grid_elements(GTK_WIDGET(iter->data), data);
            if (result != NULL) {
                g_list_free(children);
                return result;
            }
        }
        g_list_free(children);
    }

    const gchar *name = (const gchar *)data;

    if (g_strcmp0(gtk_widget_get_name(widget), name) == 0) {
        return widget;
    }

    return NULL;
}

// Correct
static void activate(GtkApplication *app, gpointer user_data) {
    GtkWidget *window;
    GtkWidget *grid;

    GtkWidget *youtube_link_label;
    GtkWidget *youtube_link_entry;
    GtkWidget *parse_button;

    GtkWidget *image_box;

    GtkWidget *song_label;
    GtkWidget *song_entry;

    GtkWidget *artist_label;
    GtkWidget *artist_entry;

    GtkWidget *uid_label;
    GtkWidget *uid_entry;

    GtkWidget *ok_button;
    GtkWidget *cancel_button;

    window = gtk_application_window_new(app);
    gtk_window_set_title(GTK_WINDOW(window), "Media Handler");
    gtk_window_set_default_size(GTK_WINDOW(window), 400, 300);
    gtk_window_set_resizable(GTK_WINDOW(window),FALSE);

    grid = gtk_grid_new();
    gtk_container_add(GTK_CONTAINER(window), grid);

    youtube_link_label = gtk_label_new("YouTube");
    youtube_link_entry = gtk_entry_new();
    gtk_widget_set_name(youtube_link_entry, "youtube_link_entry"); 
    parse_button = gtk_button_new_with_label("Parse");


    gsize image_size; 
    guchar *image_data = g_base64_decode(base64_image, &image_size); 
    GdkPixbufLoader *loader = gdk_pixbuf_loader_new(); 
    gdk_pixbuf_loader_write(loader, image_data, image_size, NULL); 
    gdk_pixbuf_loader_close(loader, NULL); 
    GdkPixbuf *pixbuf = gdk_pixbuf_loader_get_pixbuf(loader); 
    GdkPixbuf *scaled_pixbuf = gdk_pixbuf_scale_simple(pixbuf, 400, 250, GDK_INTERP_BILINEAR); 
    image_box = gtk_image_new_from_pixbuf(scaled_pixbuf);
    gtk_widget_set_name(image_box, "image_box"); 


    song_label = gtk_label_new("Song");
    song_entry = gtk_entry_new();
    gtk_widget_set_name(song_entry, "song_entry"); 

    artist_label = gtk_label_new("Artist");
    artist_entry = gtk_entry_new();
    gtk_widget_set_name(artist_entry, "artist_entry"); 

    uid_label = gtk_label_new("UID");
    uid_entry = gtk_entry_new();
    gtk_widget_set_name(uid_entry, "uid_entry"); 
    gtk_editable_set_editable(GTK_EDITABLE(uid_entry), FALSE); 
    gtk_widget_set_sensitive(uid_entry, FALSE);

    ok_button = gtk_button_new_with_label("OK");
    cancel_button = gtk_button_new_with_label("Cancel");

    gtk_widget_set_sensitive(GTK_WIDGET(ok_button), FALSE);
    gtk_widget_set_name(ok_button, "ok_button"); 

    gtk_grid_set_row_spacing(GTK_GRID(grid), 10);   
    gtk_grid_set_column_spacing(GTK_GRID(grid), 10); 

    GtkWidget *widgets[] = {youtube_link_label, song_label, artist_label, uid_label, ok_button, cancel_button};

    for (int i = 0; i < sizeof(widgets)/sizeof(widgets[0]); ++i) {
        gtk_widget_set_margin_top(widgets[i], 5);
        gtk_widget_set_margin_bottom(widgets[i], 5);
    }

    gtk_grid_attach(GTK_GRID(grid), youtube_link_label, 0, 0, 1, 1);
    gtk_grid_attach(GTK_GRID(grid), youtube_link_entry, 1, 0, 3, 1);
    gtk_grid_attach(GTK_GRID(grid), parse_button, 4, 0, 1, 1);

gtk_grid_attach(GTK_GRID(grid), image_box, 0, 1, 5, 1);
gtk_widget_set_halign(image_box, GTK_ALIGN_CENTER);

gtk_grid_attach(GTK_GRID(grid), song_label, 0, 2, 1, 1);
gtk_grid_attach(GTK_GRID(grid), song_entry, 1, 2, 4, 1);

gtk_grid_attach(GTK_GRID(grid), artist_label, 0, 3, 1, 1);
gtk_grid_attach(GTK_GRID(grid), artist_entry, 1, 3, 4, 1);

gtk_grid_attach(GTK_GRID(grid), uid_label, 0, 5, 1, 1);
gtk_grid_attach(GTK_GRID(grid), uid_entry, 1, 5, 4, 1);

gtk_grid_attach(GTK_GRID(grid), ok_button, 3, 6, 1, 1);
gtk_grid_attach(GTK_GRID(grid), cancel_button, 4, 6, 1, 1);


    gtk_widget_show_all(window);

    g_signal_connect(parse_button, "clicked", G_CALLBACK(on_parse_button_clicked), window); 
    
    g_signal_connect(ok_button, "clicked", G_CALLBACK(on_ok_button_clicked), window);
    g_signal_connect(cancel_button, "clicked", G_CALLBACK(gtk_window_close), window);
}